language: node_js

node_js:
  - lts/*

cache:
  apt: true
  directories:
    - node_modules

install:
  - yarn global add vuepress
  - yarn install
script:
  - vuepress build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  
  skip-cleanup: true
  keep-history: true
  local_dir: .vuepress/dist
  committer-from-gh: true
  on:
    branch: master

