language: node_js

sudo: false

node_js:
  - lts/*

cache:
  apt: true
  directories:
    - node_modules

install:
  - npm ci
script:
  - npm run docs:build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  local_dir: docs/.vuepress/dist
  committer-from-gh: true
  on:
    branch: master