language: node_js

sudo: false

node_js:
  - "10"

cache:
  apt: true
  directories:
    - node_modules

script:
  - npm run eslint
  - npm run build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  committer-from-gh: true
  on:
    branch: master